package jp.co.marugen.kigyoushiboudoranking;

import static android.provider.BaseColumns._ID;
import static jp.co.marugen.kigyoushiboudoranking.Constants.commpany_name;
import static jp.co.marugen.kigyoushiboudoranking.Constants.criteria_name0;
import static jp.co.marugen.kigyoushiboudoranking.Constants.criteria_name1;
import static jp.co.marugen.kigyoushiboudoranking.Constants.criteria_name2;
import static jp.co.marugen.kigyoushiboudoranking.Constants.criteria_name3;
import static jp.co.marugen.kigyoushiboudoranking.Constants.criteria_name4;
import static jp.co.marugen.kigyoushiboudoranking.Constants.criteria_name5;
import static jp.co.marugen.kigyoushiboudoranking.Constants.criteria_name6;
import static jp.co.marugen.kigyoushiboudoranking.Constants.criteria_name7;
import static jp.co.marugen.kigyoushiboudoranking.Constants.criteria_name8;
import static jp.co.marugen.kigyoushiboudoranking.Constants.criteria_name9;
import static jp.co.marugen.kigyoushiboudoranking.Constants.criteria_num0;
import static jp.co.marugen.kigyoushiboudoranking.Constants.criteria_num1;
import static jp.co.marugen.kigyoushiboudoranking.Constants.criteria_num2;
import static jp.co.marugen.kigyoushiboudoranking.Constants.criteria_num3;
import static jp.co.marugen.kigyoushiboudoranking.Constants.criteria_num4;
import static jp.co.marugen.kigyoushiboudoranking.Constants.criteria_num5;
import static jp.co.marugen.kigyoushiboudoranking.Constants.criteria_num6;
import static jp.co.marugen.kigyoushiboudoranking.Constants.criteria_num7;
import static jp.co.marugen.kigyoushiboudoranking.Constants.criteria_num8;
import static jp.co.marugen.kigyoushiboudoranking.Constants.criteria_num9;
import static jp.co.marugen.kigyoushiboudoranking.Constants.criteria_weight0;
import static jp.co.marugen.kigyoushiboudoranking.Constants.criteria_weight1;
import static jp.co.marugen.kigyoushiboudoranking.Constants.criteria_weight2;
import static jp.co.marugen.kigyoushiboudoranking.Constants.criteria_weight3;
import static jp.co.marugen.kigyoushiboudoranking.Constants.criteria_weight4;
import static jp.co.marugen.kigyoushiboudoranking.Constants.criteria_weight5;
import static jp.co.marugen.kigyoushiboudoranking.Constants.criteria_weight6;
import static jp.co.marugen.kigyoushiboudoranking.Constants.criteria_weight7;
import static jp.co.marugen.kigyoushiboudoranking.Constants.criteria_weight8;
import static jp.co.marugen.kigyoushiboudoranking.Constants.criteria_weight9;
import static jp.co.marugen.kigyoushiboudoranking.Constants.table_name;
import static jp.co.marugen.kigyoushiboudoranking.Constants.total_num;
import android.content.ContentValues;
import android.content.Context;
import android.database.sqlite.SQLiteDatabase;

public class Initial {
    private DBAdapter helper;

    public void initialization(Context context) {

        // ///////////////データベースの初期化/////////////////
        helper = new DBAdapter(context);
        SQLiteDatabase db = helper.getWritableDatabase();
        // 一旦全て削除
        db.delete(table_name, null, null);
        ContentValues values = new ContentValues();
        values.put(criteria_num0, 0);
        values.put(criteria_num1, 0);
        values.put(criteria_num2, 0);
        values.put(criteria_num3, -1);
        values.put(criteria_num4, -1);
        values.put(criteria_num5, -1);
        values.put(criteria_num6, -1);
        values.put(criteria_num7, -1);
        values.put(criteria_num8, -1);
        values.put(criteria_num9, -1);
        values.put(commpany_name, "サンプル会社A");
        values.put(_ID, 0);
        values.put(total_num, 0);
        values.put(criteria_name0, "ビジョン");
        values.put(criteria_name1, "将来性");
        values.put(criteria_name2, "給与");
        values.put(criteria_name3, "kara");
        values.put(criteria_name4, "kara");
        values.put(criteria_name5, "kara");
        values.put(criteria_name6, "kara");
        values.put(criteria_name7, "kara");
        values.put(criteria_name8, "kara");
        values.put(criteria_name9, "kara");
        values.put(criteria_weight0, 3);
        values.put(criteria_weight1, 3);
        values.put(criteria_weight2, 3);
        values.put(criteria_weight3, 3);
        values.put(criteria_weight4, 3);
        values.put(criteria_weight5, 3);
        values.put(criteria_weight6, 3);
        values.put(criteria_weight7, 3);
        values.put(criteria_weight8, 3);
        values.put(criteria_weight9, 3);
        db.insertOrThrow(table_name, null, values);

        ContentValues values2 = new ContentValues();
        values2.put(criteria_num0, 1);
        values2.put(criteria_num1, 1);
        values2.put(criteria_num2, 1);
        values2.put(criteria_num3, -1);
        values2.put(criteria_num4, -1);
        values2.put(criteria_num5, -1);
        values2.put(criteria_num6, -1);
        values2.put(criteria_num7, -1);
        values2.put(criteria_num8, -1);
        values2.put(criteria_num9, -1);
        values2.put(commpany_name, "サンプル会社B");
        values2.put(_ID, 1);
        values2.put(total_num, 3);
        values2.put(criteria_name0, "ビジョン");
        values2.put(criteria_name1, "将来性");
        values2.put(criteria_name2, "給与");
        values2.put(criteria_name3, "kara");
        values2.put(criteria_name4, "kara");
        values2.put(criteria_name5, "kara");
        values2.put(criteria_name6, "kara");
        values2.put(criteria_name7, "kara");
        values2.put(criteria_name8, "kara");
        values2.put(criteria_name9, "kara");
        values2.put(criteria_weight0, 3);
        values2.put(criteria_weight1, 3);
        values2.put(criteria_weight2, 3);
        values2.put(criteria_weight3, 3);
        values2.put(criteria_weight4, 3);
        values2.put(criteria_weight5, 3);
        values2.put(criteria_weight6, 3);
        values2.put(criteria_weight7, 3);
        values2.put(criteria_weight8, 3);
        values2.put(criteria_weight9, 3);
        db.insertOrThrow(table_name, null, values2);

        ContentValues values3 = new ContentValues();
        values3.put(criteria_num0, 2);
        values3.put(criteria_num1, 2);
        values3.put(criteria_num2, 2);
        values3.put(criteria_num3, -1);
        values3.put(criteria_num4, -1);
        values3.put(criteria_num5, -1);
        values3.put(criteria_num6, -1);
        values3.put(criteria_num7, -1);
        values3.put(criteria_num8, -1);
        values3.put(criteria_num9, -1);
        values3.put(commpany_name, "サンプル会社C");
        values3.put(_ID, 2);
        values3.put(total_num, 6);
        values3.put(criteria_name0, "ビジョン");
        values3.put(criteria_name1, "将来性");
        values3.put(criteria_name2, "給与");
        values3.put(criteria_name3, "kara");
        values3.put(criteria_name4, "kara");
        values3.put(criteria_name5, "kara");
        values3.put(criteria_name6, "kara");
        values3.put(criteria_name7, "kara");
        values3.put(criteria_name8, "kara");
        values3.put(criteria_name9, "kara");
        values3.put(criteria_weight0, 3);
        values3.put(criteria_weight1, 3);
        values3.put(criteria_weight2, 3);
        values3.put(criteria_weight3, 3);
        values3.put(criteria_weight4, 3);
        values3.put(criteria_weight5, 3);
        values3.put(criteria_weight6, 3);
        values3.put(criteria_weight7, 3);
        values3.put(criteria_weight8, 3);
        values3.put(criteria_weight9, 3);
        db.insertOrThrow(table_name, null, values3);

        helper.close();
    }
}
